# Generated by Django 4.2.6 on 2023-10-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_technologyused_project_about_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=300)),
            ],
        ),
    ]
