# Generated by Django 4.2.6 on 2023-10-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_language_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologyused',
            name='language_used',
        ),
        migrations.AddField(
            model_name='project',
            name='importance',
            field=models.CharField(choices=[(1, 'complex'), (2, 'proud of'), (3, 'easy')], default=3, max_length=1),
            preserve_default=False,
        ),
    ]
