# Generated by Django 4.2.6 on 2023-10-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_technologyused_language_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='importance',
            field=models.CharField(choices=[(1, 'complex'), (2, 'proud of'), (3, 'easy')], max_length=10),
        ),
    ]
