# Generated by Django 4.2.6 on 2023-10-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='importance',
            field=models.CharField(choices=[(1, 'complex'), (2, 'proud of'), (3, 'easy')], default='easy', max_length=10),
        ),
    ]
