# Generated by Django 4.2.6 on 2023-10-23 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_importance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languageused',
            options={'verbose_name_plural': 'Languages Used'},
        ),
        migrations.AlterModelOptions(
            name='technologyused',
            options={'verbose_name_plural': 'Technologies Used'},
        ),
        migrations.AddField(
            model_name='technologyused',
            name='language_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.languageused'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology_used',
            field=models.ManyToManyField(related_name='technologies_used', to='projects.technologyused'),
        ),
    ]
