# Generated by Django 4.2.6 on 2023-10-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_languageused_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageused',
            name='language_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
