# Generated by Django 4.2.6 on 2023-10-23 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_languageused_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageused',
            name='language_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='technologyused',
            name='language_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.languageused'),
        ),
    ]
