# Generated by Django 4.2.6 on 2023-10-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_languageused_language_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languageused',
            old_name='language_name',
            new_name='language_used',
        ),
        migrations.AlterField(
            model_name='project',
            name='technology_used',
            field=models.ManyToManyField(to='projects.technologyused'),
        ),
    ]
