# Generated by Django 4.2.6 on 2023-10-24 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_rename_language_name_languageused_language_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languageused',
            old_name='language_used',
            new_name='language_name',
        ),
    ]
