# Generated by Django 4.2.6 on 2023-10-25 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_rename_language_used_languageused_language_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='language_used',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology_used',
        ),
        migrations.AddField(
            model_name='project',
            name='language_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.languageused'),
        ),
        migrations.AddField(
            model_name='project',
            name='technology_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.technologyused'),
        ),
    ]
