# Generated by Django 4.2.6 on 2023-10-25 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_project_language_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='about_project',
            new_name='project_description',
        ),
    ]
