# Generated by Django 4.2.6 on 2023-10-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_rename_about_project_project_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(null=True, upload_to='project_images'),
        ),
    ]
