# Generated by Django 4.2.6 on 2023-10-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_remove_project_language_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(default='/project_images/no_image', null=True, upload_to='project_images'),
        ),
    ]
