# Generated by Django 4.2.6 on 2023-10-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_project_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='project_images'),
        ),
    ]
