# Generated by Django 4.2.6 on 2023-10-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_project_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='languages_used',
            field=models.ManyToManyField(related_name='projects', to='projects.languageused'),
        ),
    ]
