# Generated by Django 4.2.6 on 2023-10-26 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, default='project_images/no_image.png', null=True, upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='projects.project'),
        ),
    ]
