# Generated by Django 4.2.6 on 2023-10-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_project_technologies_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='importance',
        ),
        migrations.AddField(
            model_name='project',
            name='complexity',
            field=models.CharField(choices=[('1', 'complex'), ('2', 'challenging'), ('3', 'intermediate'), ('4', 'beginner')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies_used',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='projects.technologyused'),
        ),
    ]
