# Generated by Django 4.2.6 on 2023-10-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_project_github_link_project_hosted_project_live_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='github_link',
            new_name='repository_link',
        ),
    ]
