# Generated by Django 4.2.6 on 2023-10-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_rename_github_link_project_repository_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hostable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies_used',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.technologyused'),
        ),
    ]
