# Generated by Django 4.2.6 on 2023-10-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_project_hostable_alter_project_technologies_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='live_site',
        ),
        migrations.RemoveField(
            model_name='project',
            name='repository_link',
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(max_length=300)),
                ('repository_link', models.CharField(max_length=1000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='LiveSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=300)),
                ('site_url', models.CharField(max_length=1000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_site', to='projects.project')),
            ],
        ),
    ]
