# Generated by Django 4.2.6 on 2023-10-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_project_live_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesite',
            name='site_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repository_link',
            field=models.URLField(max_length=1000),
        ),
    ]
