# Generated by Django 4.2.6 on 2023-10-29 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0034_technologyused_user_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyused',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies_used', to=settings.AUTH_USER_MODEL),
        ),
    ]
