# Generated by Django 4.2.6 on 2023-10-29 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name_plural': 'Work Experiences'},
        ),
        migrations.AlterField(
            model_name='bulletpoint',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_points', to='about_me.experience'),
        ),
    ]
